export const users = [
  {
    id: "01H00X71C1RT2AEQVEQRQTW2BP",
    name: "Wolf Burn",
    job: "Legal Assistant",
    age: 31,
    address: "4 Vera Junction",
    parent: { mother: "Carlen", father: "Wolf" },
  },
  {
    id: "01H00X71C3965CMQHWJ6J8S4VG",
    name: "Arvy Girone",
    job: "Software Engineer IV",
    age: 72,
    address: "786 Lakewood Drive",
    parent: { mother: "Venita", father: "Arvy" },
  },
  {
    id: "01H00X71C4KD8WPPJZWTC2F6BE",
    name: "Mace Such",
    job: "Structural Analysis Engineer",
    age: 52,
    address: "1 Katie Street",
    parent: { mother: "Tanhya", father: "Mace" },
  },
  {
    id: "01H00X71C53CDMM6EZRVJ22V6Z",
    name: "Gary Kimbury",
    job: "Research Nurse",
    age: 35,
    address: "05 Bashford Junction",
    parent: { mother: "Anette", father: "Gary" },
  },
  {
    id: "01H00X71C6ZYAADYYZ7WN1ZXG7",
    name: "Jacques Possek",
    job: "Nuclear Power Engineer",
    age: 51,
    address: "0487 Independence Road",
    parent: { mother: "Madge", father: "Jacques" },
  },
  {
    id: "01H00X71C8AVEGAANBVGTKKN1N",
    name: "Gilbert Burnhard",
    job: "Occupational Therapist",
    age: 32,
    address: "599 Harbort Trail",
    parent: { mother: "Abby", father: "Gilbert" },
  },
  {
    id: "01H00X71C8NY3A0S426A2RG51Q",
    name: "Wilburt Balleine",
    job: "Assistant Media Planner",
    age: 39,
    address: "6 Sloan Point",
    parent: { mother: "Prudence", father: "Wilburt" },
  },
  {
    id: "01H00X71C9PMM1HVZ2890BY3WC",
    name: "Woodie Firby",
    job: "Speech Pathologist",
    age: 60,
    address: "64 Hanson Way",
    parent: { mother: "Meara", father: "Woodie" },
  },
  {
    id: "01H00X71CB70919NC5A4WYSDS7",
    name: "Jameson Woolvett",
    job: "Statistician III",
    age: 20,
    address: "9294 Laurel Circle",
    parent: { mother: "Nerita", father: "Jameson" },
  },
  {
    id: "01H00X71CD6RJ53QJAFWR7F9HM",
    name: "Clive Fossey",
    job: "VP Sales",
    age: 9,
    address: "6 Lakeland Street",
    parent: { mother: "Morissa", father: "Clive" },
  },
  {
    id: "01H00X71CE7J902J2HAF2RYSE7",
    name: "Kim Foulser",
    job: "Research Associate",
    age: 60,
    address: "909 Cambridge Trail",
    parent: { mother: "Roselia", father: "Kim" },
  },
  {
    id: "01H00X71CG810K4FMCQ9YCAW7D",
    name: "Donnell Prestage",
    job: "Analog Circuit Design manager",
    age: 64,
    address: "95 Reinke Road",
    parent: { mother: "Philippa", father: "Donnell" },
  },
  {
    id: "01H00X71CHQ5N54430N2VF7P10",
    name: "Nealson Rowlatt",
    job: "Automation Specialist II",
    age: 42,
    address: "50818 Dakota Place",
    parent: { mother: "Carena", father: "Nealson" },
  },
  {
    id: "01H00X71CJPY9424GW1T2ZHTYT",
    name: "Lindon Sumpton",
    job: "GIS Technical Architect",
    age: 31,
    address: "19 Rusk Alley",
    parent: { mother: "Tobi", father: "Lindon" },
  },
  {
    id: "01H00X71CKE1M0CJV46TRSRJJD",
    name: "Nollie Spoerl",
    job: "Office Assistant III",
    age: 60,
    address: "72061 High Crossing Court",
    parent: { mother: "Celeste", father: "Nollie" },
  },
  {
    id: "01H00X71CMVJ3GSS24BK6KKFHV",
    name: "Giorgio Dunbleton",
    job: "Nuclear Power Engineer",
    age: 58,
    address: "87114 Thackeray Center",
    parent: { mother: "Teddi", father: "Giorgio" },
  },
  {
    id: "01H00X71CNC6FFZZXH9YBMQPDN",
    name: "Rochester Corneljes",
    job: "Media Manager I",
    age: 35,
    address: "5 Namekagon Alley",
    parent: { mother: "Harriette", father: "Rochester" },
  },
  {
    id: "01H00X71CP4FJ7S64BA083WKSE",
    name: "Keefe Binning",
    job: "Physical Therapy Assistant",
    age: 27,
    address: "0 Blaine Plaza",
    parent: { mother: "Zorine", father: "Keefe" },
  },
  {
    id: "01H00X71CQK1809H0WMT3BW7XB",
    name: "Quincey Marder",
    job: "Analog Circuit Design manager",
    age: 62,
    address: "2556 Mcguire Plaza",
    parent: { mother: "Shantee", father: "Quincey" },
  },
  {
    id: "01H00X71CR2AYNKCZD57XY0QC3",
    name: "Earl Dunton",
    job: "Accountant IV",
    age: 53,
    address: "3372 Banding Road",
    parent: { mother: "Maudie", father: "Earl" },
  },
  {
    id: "01H00X71CSJ5VKW0Q0TQH5R2QP",
    name: "Quentin Milch",
    job: "Analog Circuit Design manager",
    age: 39,
    address: "60 Judy Avenue",
    parent: { mother: "Evelina", father: "Quentin" },
  },
  {
    id: "01H00X71CTK21716SJ0A55JEYH",
    name: "Dante Duffield",
    job: "Project Manager",
    age: 17,
    address: "6 Sachs Pass",
    parent: { mother: "Ula", father: "Dante" },
  },
  {
    id: "01H00X71CVYK31WY4V09WF00XB",
    name: "Reginald Yates",
    job: "Environmental Tech",
    age: 14,
    address: "9513 Buhler Center",
    parent: { mother: "Uta", father: "Reginald" },
  },
  {
    id: "01H00X71CWAD8KX18X0X4W5PV0",
    name: "Samson Blazey",
    job: "Human Resources Assistant IV",
    age: 61,
    address: "264 Sage Place",
    parent: { mother: "April", father: "Samson" },
  },
  {
    id: "01H00X71CX0BZYZ8TAPXPG30XW",
    name: "Arte Vinton",
    job: "Human Resources Manager",
    age: 33,
    address: "2250 Toban Road",
    parent: { mother: "Haley", father: "Arte" },
  },
  {
    id: "01H00X71CYV81PWJTDDDR4D5P8",
    name: "Pietro Sidwick",
    job: "Programmer Analyst IV",
    age: 52,
    address: "36138 Raven Point",
    parent: { mother: "Jolyn", father: "Pietro" },
  },
  {
    id: "01H00X71CZJ4Z0HWTB89QB6N3R",
    name: "Randie Tagg",
    job: "VP Marketing",
    age: 51,
    address: "460 Mayer Street",
    parent: { mother: "Vitoria", father: "Randie" },
  },
  {
    id: "01H00X71D0ZAXMZE9YXBD3991S",
    name: "Keefe Beckhouse",
    job: "Chemical Engineer",
    age: 74,
    address: "560 Mccormick Court",
    parent: { mother: "Netti", father: "Keefe" },
  },
  {
    id: "01H00X71D1MX4R144HE06D9BAX",
    name: "Dugald Froud",
    job: "Product Engineer",
    age: 32,
    address: "74919 Canary Plaza",
    parent: { mother: "Lindi", father: "Dugald" },
  },
  {
    id: "01H00X71D4WX01799FTZQW2JBZ",
    name: "Yorgos Buy",
    job: "Account Representative III",
    age: 50,
    address: "69737 Birchwood Park",
    parent: { mother: "Cynthia", father: "Yorgos" },
  },
  {
    id: "01H00X71D5BWH1TFATX7GCED7P",
    name: "Gray Woodyeare",
    job: "Safety Technician III",
    age: 55,
    address: "0187 Twin Pines Circle",
    parent: { mother: "Aubrie", father: "Gray" },
  },
  {
    id: "01H00X71D6SQSE5JKSYT67HGW4",
    name: "Aymer Naisbit",
    job: "Graphic Designer",
    age: 25,
    address: "249 Grasskamp Alley",
    parent: { mother: "Jerrine", father: "Aymer" },
  },
  {
    id: "01H00X71D8MHJ78JRBKPCFAM8W",
    name: "Thaine Wankling",
    job: "Compensation Analyst",
    age: 63,
    address: "1 Warrior Way",
    parent: { mother: "Gizela", father: "Thaine" },
  },
  {
    id: "01H00X71D8HJHMRXTYWAHFBMZA",
    name: "Juan Canwell",
    job: "Paralegal",
    age: 75,
    address: "694 Calypso Pass",
    parent: { mother: "Ainslee", father: "Juan" },
  },
  {
    id: "01H00X71DA7Y5EYA8XKJRQZTK7",
    name: "Forester Pourvoieur",
    job: "Nurse",
    age: 69,
    address: "93869 5th Way",
    parent: { mother: "Rhiamon", father: "Forester" },
  },
  {
    id: "01H00X71DBMQDWY1QXH41480ME",
    name: "Reed Caret",
    job: "Mechanical Systems Engineer",
    age: 72,
    address: "95 Longview Drive",
    parent: { mother: "Shandee", father: "Reed" },
  },
  {
    id: "01H00X71DCW47R8SA3RTNVQTXR",
    name: "Toddie Reuter",
    job: "Executive Secretary",
    age: 20,
    address: "3 Ryan Parkway",
    parent: { mother: "Patricia", father: "Toddie" },
  },
  {
    id: "01H00X71DE40T0ZHSVBSGFCH5S",
    name: "Herbie Folkerts",
    job: "Analyst Programmer",
    age: 72,
    address: "4 Anniversary Alley",
    parent: { mother: "Roseline", father: "Herbie" },
  },
  {
    id: "01H00X71DFJD04B78H774T9T7N",
    name: "Valdemar Franck",
    job: "Quality Control Specialist",
    age: 22,
    address: "79790 Moland Lane",
    parent: { mother: "Lillis", father: "Valdemar" },
  },
  {
    id: "01H00X71DGJ90X5SYYNHTRKEAS",
    name: "Briggs Zorener",
    job: "Analog Circuit Design manager",
    age: 13,
    address: "8753 Starling Place",
    parent: { mother: "Pavla", father: "Briggs" },
  },
  {
    id: "01H00X71DHRTN8G4PVG7HB0ZA3",
    name: "Kennan Folbig",
    job: "VP Sales",
    age: 72,
    address: "5 Fairview Drive",
    parent: { mother: "Evonne", father: "Kennan" },
  },
  {
    id: "01H00X71DHK0BKA374RV9QMZ5Y",
    name: "Vasily Nevet",
    job: "Software Consultant",
    age: 14,
    address: "78 Quincy Park",
    parent: { mother: "Terra", father: "Vasily" },
  },
  {
    id: "01H00X71DKTKNDZTZTDMHBG0SQ",
    name: "Tull Waterdrinker",
    job: "Geologist II",
    age: 70,
    address: "6241 Rieder Lane",
    parent: { mother: "Blakeley", father: "Tull" },
  },
  {
    id: "01H00X71DM1VBYXNVX7JVB0MS3",
    name: "Jerad Witherop",
    job: "Human Resources Manager",
    age: 10,
    address: "5218 Pepper Wood Crossing",
    parent: { mother: "Alyss", father: "Jerad" },
  },
  {
    id: "01H00X71DN2SKP65MFC39QMV0Y",
    name: "Bren Troake",
    job: "Physical Therapy Assistant",
    age: 56,
    address: "4 Summerview Way",
    parent: { mother: "Ethelin", father: "Bren" },
  },
  {
    id: "01H00X71DPKYTSSZWWKDA1S2XS",
    name: "Barret Glasner",
    job: "Cost Accountant",
    age: 56,
    address: "02 Sutherland Crossing",
    parent: { mother: "Aubine", father: "Barret" },
  },
  {
    id: "01H00X71DQ3QB8EYYFY4MVBZ2M",
    name: "Merwyn Pugsley",
    job: "Recruiting Manager",
    age: 24,
    address: "0 Village Junction",
    parent: { mother: "Cyndie", father: "Merwyn" },
  },
  {
    id: "01H00X71DR427STRGYH3AMDZ12",
    name: "Borg Sothcott",
    job: "Chemical Engineer",
    age: 49,
    address: "4087 Jenna Road",
    parent: { mother: "Fernande", father: "Borg" },
  },
  {
    id: "01H00X71DS0RKQJ1BQRKSCDCNM",
    name: "Christophe Smoote",
    job: "Food Chemist",
    age: 73,
    address: "73 Cherokee Place",
    parent: { mother: "Ranee", father: "Christophe" },
  },
  {
    id: "01H00X71DTG811RJMZP35KRMCE",
    name: "Doug Langman",
    job: "Social Worker",
    age: 10,
    address: "63 Canary Lane",
    parent: { mother: "Annabela", father: "Doug" },
  },
];
